# sudo: false
# dist: trusty
# addons:
#   apt_packages:
#     - graphicsmagick
#     - ghostscript
os: osx
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_install:
  - brew update
  - brew install graphicsmagick
  - brew install ghostscript
install:
  - npm install
# before_script:
script:
  - npm run tsc
  - npm run lint
  - npm run test
